fix: canStale should return false if Cache-Control: must-revalidate is present #507
arthurfiorette/axios-cache-interceptor pull request #510
Opened 2023-02-27 19:08 UTC by rishisundar

### Description
This PR contains the following changes:
 -  Fix for incorrect behavior of canStale function.
 - Updated test cases.

### Relevant Issue:
 #507

2023-02-27 19:12 UTC, rishisundar commented
@arthurfiorette can you please give me some pointer on why `tests modifiedSince using cache timestamp` test fails 🤔 ?

2023-02-27 21:36 UTC, arthurfiorette commented
> @arthurfiorette can you please give me some pointer on why `tests modifiedSince using cache timestamp` test fails 🤔 ?

What the debug option prints when running this test?

2023-02-28 12:54 UTC, arthurfiorette requested changes

2023-02-28 12:54 UTC, arthurfiorette commented on src/storage/build.ts
> +    !mustRevalidate
Can you check separately if this is strict equal to true? And if so return early false?

2023-02-28 12:54 UTC, arthurfiorette commented on test/header/cache-control.test.ts
> +    const mustRevalidate = defaultHeaderInterpreter({
this check doesn't make sense, `must-revalidate` just prevent the storage value become stale.

2023-02-28 12:54 UTC, arthurfiorette commented on test/interceptors/request.test.ts
> +    const axios = mockAxios({}, { 'cache-control': 'max-age=1, must-revalidate' });
Same here, this whole check doesn't make sense, can you recreate it checking if the `must-revalidate` makes `canStale` return false always?
Like one normal request without, a request with `must-revalidate` it and another with `etag` and/or `lastModified` enabled?

2023-02-28 12:54 UTC, arthurfiorette commented on test/interceptors/request.test.ts
> +    const axios = mockAxios({}, { 'cache-control': 'max-age=1, must-revalidate' });
Said `etag` and/or `lastModified` because they should normally make a storage value go to `stale`.

2023-02-28 12:54 UTC, arthurfiorette commented on src/header/interpreter.ts
> +    const { noCache, noStore, maxAge, immutable } = parse(String(cacheControl));
To your knowledge, is another header handling missing or wrongly interpreted?

2023-04-09 15:53 UTC, arthurfiorette commented
PR out of date and implemented by 22870d7.

2023-04-09 15:53 UTC, closed without merging