Add 'cloneData' option to buildMemoryStorage
arthurfiorette/axios-cache-interceptor pull request #581
Opened 2023-06-28 14:21 UTC by bhallionOhbibi

See [issue 580](https://github.com/arthurfiorette/axios-cache-interceptor/issues/580) for more details

2023-06-28 16:14 UTC, bhallionOhbibi commented
Looks like there is some issue with the CI

2023-06-28 18:47 UTC, arthurfiorette requested changes

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
> +  storeClone = false
```suggestion
```

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
>   * @param {boolean} cloneData If the data returned by `find()` should be cloned to avoid
```suggestion
 * @param {boolean | 'double'} cloneData If the data returned by `find()` should be cloned to avoid
```

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
> + *   mutating the original data outside the `set()` method. Disabled is default
```suggestion
 *   mutating the original data outside the `set()` method. Use `'double'` to also clone `set()` return value. Disabled is default
```

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
> +      if (storeClone && value !== undefined) {
```suggestion
      if (cloneData === 'double' && value !== undefined) {
```

2023-06-28 18:47 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +    const storage = buildMemoryStorage(false, false, false, true);
```suggestion
    const storage = buildMemoryStorage('double', false, false);
```

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
>    cloneData = false,
```suggestion
  cloneData: boolean | 'double' = false,
```

2023-06-28 18:47 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +
This check below checks if the `find()` clone is working. Please add expect statements with direct access to `storage.data`.

2023-06-28 18:47 UTC, arthurfiorette commented on src/storage/memory.ts
>   * @param {boolean} cloneData If the data returned by `find()` should be cloned to avoid
Please change the documentation to reflect this changes too.

2023-06-28 18:49 UTC, arthurfiorette commented
The CI failed because of linting, please run `pnpm lint -- --fix` and `pnpm format` before push to lint your code.

2023-06-28 18:49 UTC, arthurfiorette commented
I added a review to update the `cloneData` property instead of creating a new one. Overall, suuper thanks for your time in this PR :)

2023-06-29 05:56 UTC, bhallionOhbibi commented
Thanks for your review. This is the first time writing typescript code. As yo ucan expect, my local configuration is not exactly mature right now :sweat_smile: 

I updated the test, but I'm not sure if this is enough, please let me know what you think.

About `storeClone`:
I removed it. It was an attempt to be a bit more explicit, as I find 'double' on `cloneData` less explicit. In the other hand, 'double' on `cloneData` limit amount of parameters and allow us to use the new option without adding `cleanupInterval` and `maxEntries` to false every time.
You decide what's best for this library and adding 'double' to `cloneData` seems like a fine typescript way of adding functionnality.

Another note about this whole clone thing. I really think that the `double` options should be the default value. I would argue that anyone trying this library for the first time might have a hard time understanding why their `axios.get` calls doesnt returns the same data every time. And suddenly having to check for `cached` property or having to provide additionnal configuration might block some users from using the library altogether.

2023-06-29 13:54 UTC, arthurfiorette requested changes

2023-06-29 13:54 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +      expect(storage.data['key'].state).toBe('cached');
```suggestion
      expect(storage.data['key']!.state).toBe('cached');
```

Use the `!` operator and remove these if checks.

2023-06-29 13:54 UTC, arthurfiorette commented on src/storage/memory.ts
> +      if (cloneData === 'double' && value !== undefined) {
```suggestion
      /* istanbul ignore if 'only available on super recent browsers' */
      if (cloneData === 'double' && value !== undefined) {
```

Add this comment to code coverage skip the structuredClone test

2023-06-29 13:54 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +  it('not allow changes by value reference before', async () => {
```suggestion
  it('ensures set() also clones data when cloneData is double', async () => {
```

2023-06-29 14:04 UTC, arthurfiorette commented
> adding 'double' to cloneData seems like a fine typescript way

Yeah! I'm just not satisfied enough with the double name, any synonyms comes to your mind?

> I really think that the double options should be the default value. 

They may be, but i'd only make them default on the next major version as it will be a breaking change... Also, I'm not sure how the GC will behave on data being cloned everywhere.

2023-06-30 10:38 UTC, bhallionOhbibi commented
Instead of `double` I suggested `all`.

But it would be more explicit and also more configurable to use an enum.
Perhaps something like:
- `onSet`
- `onGet`

Where the user can specify one, both or none of the options (so an array of string maybe ?).
I think this aproach is the best, it wont break compatibility if you want to add clone to another method.
Let the user specify: `['onSet', 'onGet']`

I dont know how one would neatly implement this in typescript tho.

2023-07-01 21:28 UTC, arthurfiorette requested changes
some linting

2023-07-01 21:28 UTC, arthurfiorette commented on src/storage/memory.ts
> +      if (cloneData === 'double' && value !== undefined) {
```suggestion
      if (cloneData === 'double') {
```

value will never get undefined here

2023-07-01 21:28 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +    expect(storage.data['key']!.state).toBe('cached');
```suggestion
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    expect(storage.data['key']!.state).toBe('cached');
```

2023-07-01 21:28 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +    expect(storage.data['key']!.data).not.toBeNull();
```suggestion
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    expect(storage.data['key']!.data).not.toBeNull();
```

2023-07-01 21:28 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +    expect(storage.data['key']!.data!.data).toBe('data');
```suggestion
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    expect(storage.data['key']!.data!.data).toBe('data');
```

2023-07-01 21:28 UTC, arthurfiorette commented on test/storage/memory.test.ts
> +    await storage.set('key', {
```suggestion

    await storage.set('key', {
```

2023-07-01 22:35 UTC, merged

2023-07-01 22:35 UTC, arthurfiorette commented
Thanks!